CLN-4776 Add integration test for only-blob-upload option for storage-deploy-action
leanix/storage-deploy-action pull request #29
Opened 2021-12-02 13:13 UTC by mplesec

https://leanix.atlassian.net/browse/CLN-4776

Almost forgot of this, but as promised this PR adds a test for the `only-blob-upload` option.

2021-12-02 14:37 UTC, dan-leanix requested changes

2021-12-02 14:37 UTC, dan-leanix commented on .github/workflows/test.yml
> +        if: steps.only-blob-upload.outputs != 'Deployed to Azure Blob Storage storage-deploy-action-public. Skipping deploy to Azure File Storage.'
```suggestion
        if: steps.only-blob-upload.outputs != 'Deployed to Azure Blob Storage leanixwesteuropetest. Skipping deploy to Azure File Storage.'
```

2021-12-02 15:02 UTC, mplesec commented
@dan-leanix I see that there's a problem with the additional regions that were set up:

https://github.com/leanix/storage-deploy-action/runs/4396664548?check_suite_focus=true
```
currentRegion:  { name: 'westeurope', short: 'eu' }
Now deploying to leanixwesteuropetest!
Now deploying to Azure Blob Storage leanixwesteuropetest.
Finished deploying to region westeurope.
currentRegion:  { name: 'eastus', short: 'us' }
Storage Account leanixeastustest does not exist.
Error: ERROR: Storage account 'leanixeastustest' not found.
INFO: Command ran in 2.208 seconds (init: 0.152, invoke: 2.056)

currentRegion:  { name: 'canadacentral', short: 'ca' }
Storage Account leanixcanadacentraltest does not exist.
Error: ERROR: Storage account 'leanixcanadacentraltest' not found.
INFO: Command ran in 2.012 seconds (init: 0.150, invoke: 1.862)

currentRegion:  { name: 'australiaeast', short: 'au' }
Storage Account leanixaustraliaeasttest does not exist.
Error: ERROR: Storage account 'leanixaustraliaeasttest' not found.
INFO: Command ran in 2.461 seconds (init: 0.148, invoke: 2.313)

currentRegion:  { name: 'germanywestcentral', short: 'de' }
Storage Account leanixdetest does not exist.
Error: ERROR: Storage account 'leanixdetest' not found.
INFO: Command ran in 2.101 seconds (init: 0.159, invoke: 1.942)
```

2021-12-02 15:29 UTC, dan-leanix commented
@mplesec That is not a problem you just need to call the storage-deploy-action with the region parameter and then this should work. ;-)

2021-12-02 15:30 UTC, dan-leanix requested changes

2021-12-02 15:30 UTC, dan-leanix commented on .github/workflows/test.yml
> +          only-blob-upload: true
```suggestion
          environment: test
          region: westeurope
          only-blob-upload: true
```

2021-12-06 09:41 UTC, dan-leanix commented
@mplesec I would not waste any time here further. Just close the PR. If this blob only upload would not work, you would have experienced it.

Otherwise, if you want to do this. The output you reference returns an `Object`.

Furthermore, don't turn off the silent mode as otherwise we expose the SAS token to the general public here.

2021-12-06 09:55 UTC, mplesec commented
I give up trying to get this to work. If anyone else wants to take a look at it and get the jobs to pass, please do. Closing.

What fails is this:
![Screenshot 2021-12-06 at 10 54 30](https://user-images.githubusercontent.com/9392804/144825527-599bd4fb-4915-4887-9386-7a2085ab55a8.png)

2021-12-06 09:55 UTC, closed without merging