INVT-9468 Add Versioning
leanix/storage-deploy-action pull request #9
Opened 2021-02-17 08:17 UTC by yae-leanix

Story: https://leanix.atlassian.net/browse/INVT-9466
- Preparing the introduction of a rollback mode

2021-02-17 15:15 UTC, konstantintieber commented on index.js
> +            await exec.exec('./azcopy', [
Here's how I interpret this `./azcopy` comand: "overwrite the contents of the `index.html` on the provided `container` with the contents of the `index_${releaseVersion}.html`"

Is that correct?

And that `sourceDirectory/index.html` is what our [cdn-proxy](https://github.com/leanix/cdn-proxy) routes any requests to, correct?

2021-02-18 06:25 UTC, yae-leanix commented on index.js
> +            await exec.exec('./azcopy', [
See: https://docs.microsoft.com/en-us/azure/storage/common/storage-ref-azcopy-sync?toc=/azure/storage/blobs/toc.json

In this case I am using the `azcopy sync` which `Replicates the source location to the destination location.`.  From my understanding `sourceDirectory/index.html` is the path to the locally build application which now needs to be moved into the CDN container. The command is saying `store the locally build index.html as index_${version}.html in the CDN container`.

2021-02-18 06:26 UTC, yae-leanix commented on index.js
> +            await exec.exec('./azcopy', [
So ``https://${storageAccount}.blob.core.windows.net/${container}/index_${releaseVersion}.html` is what the cdn-proxy routes any requests to.

2021-02-18 07:29 UTC, perbernhardt requested changes
Looks promising! Some remarks though:
1. You definitively need to run "update-dist.sh" because the action actually runs the "dist/index.js" which has all batteries included (e.g. npm packages compiled into it).
2. What about projects that don't have an index.html? E.g. they could be a WebComponent only offering an "main.js". I guess this somehow follows the files we also exclude from caching, see https://github.com/leanix/infrastructure-storage/blob/master/leanix.tf#L134 Perhaps we should copy all of them and only if they exists. As an alternative you could introduce a parameter to the action that lists all files that need to be "versioned".
3. You can add tests to the "test.yml" github workflow file. Just be creative in what you test. The workflow already uses the action within the repository to deploy files to a storage container. So you can actually look into them during the workflow.

2021-02-18 08:42 UTC, yae-leanix commented on index.js
> +            await exec.exec('./azcopy', [
By the way `sync` does not support what I wanted to do. I was required to rely on `cp` to perform the action that I wanted.

2021-02-19 13:26 UTC, yae-leanix commented
I changed the versioning concept, as there are a lot of files that are not fingerprinted during the build step.
So in order to perform a complete rollback, which means restoring all files without a fingerprint, I decided it would be the easiest to create a folder for each new version (called `v${versionNumber}`) that contains all files that shall be deployed as part of the release. The rollback mechanism then just copies all files from the corresponding version folder into the root directory, overwriting all files without a fingerprint.

@perbernhardt do you think this is a good approach in this case? For the pathfinder web deployment there are hundreds if not a few thousands of files without a fingerprint.

2021-02-19 13:27 UTC, yae-leanix commented
I will be adding to the README once we have decided on how to do the versioning.

2021-02-19 13:44 UTC, yae-leanix commented
As for tests: I just added an html file and could verify based on the pipeline run that we indeed create the version tags and the versioned folder within the Azure container.

2021-02-19 14:55 UTC, perbernhardt reviewed
@yae-leanix thanks for your proposal! I am actually not too happy with this approach.
So first of all, any approach to rollback will NOT work for any file that is being cached by the CDN. Or the other way around: We will always only be able to rollback the files listed in here: https://github.com/leanix/infrastructure-storage/blob/master/leanix.tf#L134
And that brings me to the other problem: I was against listing a lot of files there in the first place. I actually wonder why we would ever need something else then an "index.html" (for a webpage) or a "main.js" (for a webcompont). When listing more files as exceptions to the caching, we agreed that we only do that because we did not yet understand how to "version" them in the first place. So I would prefer to work on reducing the number of uncached files and then be able to "rollback" by simply renaming only one file.

2021-02-19 15:04 UTC, konstantintieber commented
> So I would prefer to work on reducing the number of uncached files and then be able to "rollback" by simply renaming only one file.

The length of the list of uncached files is a valid concern. @yae-leanix most files that we do not fingerprint today will only cause issues in a rollback for special cases. I think we could go with only versioning index.js and main.js inside of the storage-deploy-action and move the problem of unfingerprinted files back into the responsibility of the pathfinder-web monorepo.

Looking at the build artifact that we deploy to cdn in producton it seems that all files in our `assets` directory are affected today. Link to download the artifact from [the latest release](https://github.com/leanix/leanix-pathfinder-web/runs/1935221876): [Link](https://github.com/leanix/leanix-pathfinder-web/suites/2076760053/artifacts/42050931)

![image](https://user-images.githubusercontent.com/46342664/108521518-1835b580-72cc-11eb-987a-944d0c585443.png)

2021-02-19 15:13 UTC, yae-leanix commented
Oh I did not think about the caching problems. Thanks for clarifying that.
We would now only version the `index.html` or `main.js` file.

I noticed that the release pipeline of pathfinder-web currently still creates release tags, even if the release-docker-image-action is not executed. I think this might cause issues, if this PR is merged.
@konstantintieber It seems the action is used in https://github.com/leanix/leanix-pathfinder-web/blob/bdf7a2f9594438e1b56e3b487f661e7b9f113a69/.github/workflows/storybook.yml#L52. Do you know if it would be fine to remove that step from the pipeline?

2021-02-19 15:15 UTC, konstantintieber commented
> I noticed that the release pipeline of pathfinder-web currently still creates release tags, even if the release-docker-image-action is not executed. I think this might cause issues, if this PR is merged.

That is because Storybook is actually still deployed with docker and not with cdn. That workflow is independent from the pathfinder-web release

2021-02-19 15:28 UTC, yae-leanix commented on index.js
> +            await git.tag([releaseVersionTag, process.env.GITHUB_REF]);
Only tag if we deploy to production. Action input might need to specify if this is a production deployment or not.

2021-02-19 15:28 UTC, yae-leanix commented on index.js
> +            const releaseVersionTag = `${versionTagPrefix}${releaseVersion}`;
Tag should also include the microfrontend name, else we cannot distinguish the release tags! The microfrontend name must be passed as input to the action.

2021-02-19 16:07 UTC, superquadratic commented
> most files that we do not fingerprint today will only cause issues in a rollback for special cases

While I do think "swapping" only the `index.html` or `main.js` is the right approach, I would not feel safe using this mechanism for pf-web. Because it's not actually rolling back but creating a new state that is a mix of the old and the new state (e.g. old application code with new polyfills – if we somehow screwed up our polyfills so that the whole app fails on one browser, the rollback would not have any effect). I would feel more confident doing a new deployment. It might take a bit longer, but the outcome is more predictable. And if the cache is working correctly, nothing would actually be built, so it should even be quite fast...

But as I said, I still think it's the right approach. I'm just not sure if I'm brave enough to use it with a project where not all assets are versioned & cache-busted properly.

2021-02-22 06:09 UTC, perbernhardt commented on index.js
> +            await git.tag([releaseVersionTag, process.env.GITHUB_REF]);
Non-Production deployment may also make use of versions I'd say. In other words: It would be a pity if removing it for test would make a difference or would fix something...

2021-02-22 06:10 UTC, perbernhardt commented on index.js
> +            const releaseVersionTag = `${versionTagPrefix}${releaseVersion}`;
@konstantintieber Here we are again, monorepo ;-) We already discussed the necessity of the microfrontend-name in the action. I absolutely dislike this, because it makes only sense for pathfinder and its monorepo... :-(

2021-02-22 06:15 UTC, perbernhardt commented
What I noticed: Although some of the files do not have a version in their filename, they do have a version when being requested from the CDN: E.g. we load https://demo-eu.leanix.net/workspace/assets/polyfills/classList.min.js?v=852aba7118 so with a GET version attached. The files are cached by the CDN with the GET parameters INCLUDED! That means that when the index.html (or someone after that), uses a previous version again, the CDN will deliver the previous cached version. Might not be as good as having a version in the filename, but should still work...

2021-02-22 06:39 UTC, yae-leanix commented on index.js
> +            const releaseVersionTag = `${versionTagPrefix}${releaseVersion}`;
@perbernhardt This sounds to me like an argument for actually putting the tagging mechanism and version generation into a separate action. This way this action is kept generic.

2021-02-22 07:01 UTC, perbernhardt commented on index.js
> +            const releaseVersionTag = `${versionTagPrefix}${releaseVersion}`;
Not sure about that. We just need to remember, that this action (storage-deploy-action) is used also by non-monorepo projects...

2021-02-22 08:52 UTC, superquadratic commented
> That means that when the index.html (or someone after that), uses a previous version again, the CDN will deliver the previous cached version.

I would say "the CDN _probably_ delivers the cached version", unless for some reason we get a cache miss and then get the new version? Also, only some of the query params use a fixed value (the commit hash of the release), others use a timestamp to bust the cache for every request.

2021-02-24 13:02 UTC, yae-leanix commented on index.js
> +            const releaseVersionTag = `${versionTagPrefix}${releaseVersion}`;
Alright. We can make this an optional parameter then.

2021-02-24 13:05 UTC, yae-leanix commented
@superquadratic Would you be fine with us adding the versioning for `index.html` and `main.js` as well as a rollback mode within this action, such that we have the code in place.
Based on your replies I gathered that we are probably not yet at a place, where a rollback is guaranteed to be successful. However I still see value in getting the mentioned logic into this action, even if we are not yet supposed to use the rollback in production.

2021-02-24 13:17 UTC, konstantintieber commented
I found a bug in the `lxAttributeTranslation` pipe:
![image](https://user-images.githubusercontent.com/46342664/109006057-edbc7180-76aa-11eb-9c57-1556457c8e28.png)

For fields that have no translation, it should fallback to the untranslated DataModel name.

2021-02-24 13:19 UTC, superquadratic commented
@yae-leanix Yes, absolutely! I think I came across more critical than I wanted to. I just wanted to discuss the potential issues. Having the rollback mechanism in place is a very valuable tool, thank you for figuring out the right way and building it! 🙏 

It will be useful for all the (micro) frontends, and for the smaller ones I think it's feasible to have all assets versioned quite soon, so that we get a 100% reliable rollback there. And even for pathfinder-web I believe that there can be situations where we want to roll back, even if the resulting state is not _exactly_ the state we had before. It might not be a "no-brainer" mitigation, but if we have a look at a release and see that it only includes application code (which is quite likely), rolling back should be the fastest and easiest mitigation (by far).

2021-02-24 13:35 UTC, yae-leanix commented on index.js
> +            const releaseVersionTag = `${versionTagPrefix}${releaseVersion}`;
I added an optional parameter in 27c57e2. I see that this makes the action less general. However the name will be necessary within our monorepo. Sadly I do not see another way of doing it. Non-monorepo projects can still use the action just without passing any microfrontend name.

2021-02-24 13:36 UTC, yae-leanix commented on index.js
> +            await git.tag([releaseVersionTag, process.env.GITHUB_REF]);
I agree.

2021-02-24 13:39 UTC, yae-leanix commented
@perbernhardt Is the current state of the action okay for you?
The action now calculates a version tag that might depend on a passed microfrontend name. Otherwise it uses the format from the docker action.
We only version the `index.html` and `main.js` files, if they exist. Getting a fingerprint into each file of pathfinder web will be a future problem, that we should not care about within this action. We can still get a lot of use out of adding this code.

I will add the rollback mode within a separate PR.

2021-02-24 15:12 UTC, perbernhardt commented on index.js
> +            const releaseVersionTag = `${versionTagPrefix}${releaseVersion}`;
I can totally live with the optional parameter! As you said: We obviously need it as long as we have the monorepo 👍

2021-02-24 15:24 UTC, perbernhardt approved these changes
Thank you, looks great! 👍

2021-02-24 15:24 UTC, perbernhardt commented on index.js
> +            const releaseVersionIdentifier = `${microfrontend !== '' ? microfrontend + '_' : ''}${releaseVersion}`;
I guess the microfrontend name is not needed here, but it does not break either. So feel free to keep it.

2021-02-24 15:27 UTC, perbernhardt commented on .github/workflows/test.yml
> +          microfrontend: test-microfrontend
By the way: Later on we might want to really test the rollback here. Rough idea of steps:
- ....
- deploy
- curl cdn to verify deployment
- change something in the index.html/main.js & commit it
- deploy again
- curl cdn to verify the changed deployment
- checkout previous version
- run rollback action
- curl cdn to verify the rolled back deployment

Should all be possible within one github workflow as long as you do not "push" ;-)

2021-02-25 06:35 UTC, merged

2021-02-25 09:45 UTC, yae-leanix commented
I will reopen this and only merge after I have adapted our github workflows to provide git working copy.

2021-02-25 09:50 UTC, superquadratic commented
> to provide git working copy

Is there maybe another way of doing this without requiring a working copy, like getting and creating the tags using the GitHub API? That would make using this action less error prone and allow more flexibility when structuring release pipelines (e.g. the way that works nicely for pf-web, that we now would have to change)...

2021-02-25 09:53 UTC, yae-leanix commented
I will improve my current work in https://github.com/leanix/storage-deploy-action/pull/11.
@superquadratic I agree that this would be the better approach. I will do some research and get back to you.